### PR TITLE
PyDelhi presentation completed.

### PR DESCRIPTION
**Pull request by shashankaryan**

### CODE REVIEW

**Comment by CuriousLearner** [comment]
@shashankaryan Please move all images to `img` folder

**Comment by shashankaryan** [comment]
there were both images and a video. so, all moved to media folder.

**Comment by CuriousLearner** [comment]
screen shot 2017-02-15 at 12 21 45 am
Spelling of Sponsors is incorrect in both slide as well as the image. Please fix that.

@shashankaryan

**Comment by shashankaryan** [comment]
Spelling corrected.

**Comment by CuriousLearner** [comment]
Thank you so much. There are still some minor changes, that I will fix myself.

Thanks for your work @shashankaryan

**Comment by shashankaryan** [comment]
Thanks for merging. I learned many new stuffs while making this presentation. Thanks for giving this opportunity @CuriousLearner.

**Pull request merged**
